Readme update and group codes into functions
* Updated readme to provide more info regarding installation steps
* avrdude-autoreset: Added "Ignore broken pipe error if done uploading" message
* avrdude-autoreset: Double quote array expansion to avoid element re-splitting

diff --git a/avrdude-autoreset b/avrdude-autoreset
--- a/avrdude-autoreset
+++ b/avrdude-autoreset
@@ -1,3 +1,5 @@
 #!/bin/sh
+#/usr/bin/avrdude-autoreset
 
-strace -o "|autoreset" -eioctl /usr/bin/avrdude-original $@
+strace -o "|autoreset" -eioctl /usr/bin/avrdude-original "$@"
+echo "Ignore broken pipe errors if Done Uploading"
